
import React, { useState, useEffect } from 'react';
import { XCircle, Database, Settings, Zap, AlertTriangle, CheckCircle, Copy } from './Icons';
import { storage } from '../services/storage';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: () => void;
}

const SettingsModal: React.FC<SettingsModalProps> = ({ isOpen, onClose, onSave }) => {
  const [sbUrl, setSbUrl] = useState('');
  const [sbKey, setSbKey] = useState('');
  const [showSql, setShowSql] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const sb = storage.getSupabaseConfig();
      setSbUrl(sb.url);
      setSbKey(sb.key);
    }
  }, [isOpen]);

  const SQL_CODE = `CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  location TEXT,
  link TEXT,
  requirement TEXT,
  type TEXT
);
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON jobs FOR ALL USING (true) WITH CHECK (true);`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md">
      <div className="bg-[#111116] border border-[#27272a] w-full max-w-lg p-8 rounded-3xl shadow-2xl animate-in fade-in zoom-in duration-300">
        <div className="flex justify-between items-center mb-8">
          <h2 className="text-2xl font-black text-white flex items-center gap-3 italic uppercase tracking-tighter">
            <Database className="w-6 h-6 text-blue-500" /> 核心连接配置
          </h2>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors">
            <XCircle className="w-8 h-8" />
          </button>
        </div>

        <div className="space-y-8 max-h-[70vh] overflow-y-auto pr-4 custom-scrollbar">
          <div className="bg-blue-500/5 border border-blue-500/20 p-4 rounded-xl">
             <div className="flex items-center gap-2 mb-2">
                <Zap className="w-4 h-4 text-blue-400" />
                <h4 className="text-sm font-bold text-blue-400 uppercase">Gemini 智能引擎</h4>
             </div>
             <p className="text-[11px] text-gray-400 leading-relaxed">系统已由服务端注入 Gemini 3.0 Pro 核心权限，简历解析与智能选岗已就绪。</p>
          </div>

          <div className="space-y-5">
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest">Supabase 云端数据库</h3>
            <div>
              <label className="block text-[10px] text-gray-500 font-bold uppercase mb-2">Project URL</label>
              <input
                type="text"
                value={sbUrl}
                onChange={(e) => setSbUrl(e.target.value)}
                placeholder="https://your-project.supabase.co"
                className="w-full bg-black/40 border border-[#333] rounded-xl px-4 py-3 text-white text-sm focus:border-blue-500 focus:outline-none transition-all"
              />
            </div>
            <div>
              <label className="block text-[10px] text-gray-500 font-bold uppercase mb-2">Service Role / Anon Key</label>
              <input
                type="password"
                value={sbKey}
                onChange={(e) => setSbKey(e.target.value)}
                placeholder="eyJhbG..."
                className="w-full bg-black/40 border border-[#333] rounded-xl px-4 py-3 text-white text-sm focus:border-blue-500 focus:outline-none transition-all"
              />
            </div>
          </div>

          <div className="pt-4 border-t border-white/5">
            <button 
              onClick={() => setShowSql(!showSql)}
              className="text-[11px] text-blue-500 hover:text-blue-400 font-bold flex items-center gap-1 mb-4"
            >
              {showSql ? '隐藏数据库安装指令' : '如何设置 Supabase 数据库表？'}
            </button>
            
            {showSql && (
              <div className="relative group">
                <pre className="bg-black/60 p-4 rounded-xl text-[10px] font-mono text-gray-400 overflow-x-auto border border-white/5 mb-4 leading-relaxed">
                  {SQL_CODE}
                </pre>
                <button 
                  onClick={() => { navigator.clipboard.writeText(SQL_CODE); alert('SQL 已复制！请在 Supabase SQL Editor 执行。'); }}
                  className="absolute top-2 right-2 p-2 bg-white/10 rounded-lg hover:bg-white/20 transition-all"
                >
                  <Copy className="w-4 h-4 text-white" />
                </button>
              </div>
            )}
          </div>

          <button
            onClick={() => {
              storage.setSupabaseConfig(sbUrl, sbKey);
              onSave();
              onClose();
            }}
            className="w-full py-4 bg-white text-black rounded-xl font-bold text-sm hover:bg-blue-600 hover:text-white transition-all shadow-xl active:scale-95"
          >
            保存并强制刷新同步
          </button>
        </div>
      </div>
    </div>
  );
};

export default SettingsModal;
