
import React, { useState } from 'react';
import { XCircle, Settings, Zap, Cpu, Server, ShieldCheck, Copy, CheckCircle, AlertTriangle } from './Icons';
import { UserRole } from '../types';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: () => void;
  userRole: UserRole;
}

const SettingsModal: React.FC<SettingsModalProps> = ({ isOpen, onClose, userRole }) => {
  const [showSql, setShowSql] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const INIT_SQL = `-- 阿里云 RDS PostgreSQL 初始化脚本
-- 请在阿里云 DMS 控制台或第三方客户端执行

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  location TEXT DEFAULT '全国',
  link TEXT DEFAULT '',
  requirement TEXT DEFAULT '',
  type TEXT DEFAULT ''
);

-- 开启安全策略 (可选)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow All" ON jobs FOR ALL USING (true);`;

  const copySql = () => {
    navigator.clipboard.writeText(INIT_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4">
      <div className="bg-[#0c0c10] border border-[#27272a] w-full max-w-lg p-8 rounded-3xl shadow-[0_0_50px_-12px_rgba(255,106,0,0.3)] animate-in fade-in zoom-in duration-300">
        <div className="flex justify-between items-center mb-6 border-l-4 border-[#ff6a00] pl-4">
          <h2 className="text-xl font-black text-white flex items-center gap-3 italic uppercase tracking-tighter">
            <Server className="w-5 h-5 text-[#ff6a00]" /> 阿里云官方 RDS 配置
          </h2>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors">
            <XCircle className="w-7 h-7" />
          </button>
        </div>

        <div className="space-y-6 max-h-[70vh] overflow-y-auto pr-2 custom-scrollbar">
          <div className="p-4 bg-[#ff6a00]/10 border border-[#ff6a00]/20 rounded-xl">
             <div className="flex items-center gap-3 mb-2">
                <ShieldCheck className="w-4 h-4 text-[#ff6a00]" />
                <p className="text-[11px] font-bold text-[#ff6a00] uppercase">阿里云直连模式</p>
             </div>
             <p className="text-[10px] text-gray-400 leading-relaxed">
                正在接入 <span className="text-white">阿里云 PostgreSQL</span>。
                请确保 RDS 白名单已开放外网访问，并在 Zeabur 设置好 API 代理。
             </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-[11px] font-bold text-gray-400 uppercase tracking-widest">落地步骤：</h3>
            <div className="grid grid-cols-1 gap-2 text-[10px] text-gray-400">
               <div className="flex gap-2 p-2 bg-white/5 rounded">
                  <span className="text-[#ff6a00] font-black">01</span>
                  <span>在阿里云控制台开启“申请外网地址”。</span>
               </div>
               <div className="flex gap-2 p-2 bg-white/5 rounded">
                  <span className="text-[#ff6a00] font-black">02</span>
                  <span>白名单添加 0.0.0.0/0。</span>
               </div>
               <div className="flex gap-2 p-2 bg-white/5 rounded">
                  <span className="text-[#ff6a00] font-black">03</span>
                  <span>复制下方 SQL 在“数据管理 DMS”中执行。</span>
               </div>
            </div>
          </div>

          <div className="space-y-3">
             <div className="flex justify-between items-center">
                <h3 className="text-[10px] font-bold text-gray-500 uppercase flex items-center gap-2">
                   <Cpu className="w-3 h-3" /> 初始化 SQL 脚本
                </h3>
                <button 
                  onClick={() => setShowSql(!showSql)}
                  className="text-[9px] text-[#ff6a00] font-black uppercase hover:text-white transition-colors"
                >
                  {showSql ? '[ 隐藏 ]' : '[ 显示 SQL ]'}
                </button>
             </div>

             {showSql && (
                <div className="relative group animate-in slide-in-from-top-2">
                   <pre className="bg-black/60 border border-white/5 p-4 rounded-xl text-[9px] font-mono text-gray-400 overflow-x-auto leading-relaxed">
                      {INIT_SQL}
                   </pre>
                   <button 
                    onClick={copySql}
                    className="absolute top-2 right-2 p-2 bg-white/5 hover:bg-white/10 rounded-lg transition-all"
                   >
                     {copied ? <CheckCircle className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5 text-gray-400" />}
                   </button>
                </div>
             )}
          </div>

          <button
            onClick={onClose}
            className="w-full py-4 bg-[#ff6a00] text-white rounded-xl font-bold text-xs uppercase hover:bg-white hover:text-black transition-all active:scale-95 shadow-lg shadow-[#ff6a00]/20"
          >
            保存配置并同步
          </button>
        </div>
      </div>
    </div>
  );
};

export default SettingsModal;
