
import React, { useState } from 'react';
import { XCircle, Server, ShieldCheck, Copy, CheckCircle, Zap, Database } from './Icons';
import { UserRole } from '../types';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: () => void;
  userRole: UserRole;
}

const SettingsModal: React.FC<SettingsModalProps> = ({ isOpen, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // 极简版 SQL，配合 Docker 部署使用
  const INIT_SQL = `CREATE TABLE IF NOT EXISTS jobs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMPTZ DEFAULT NOW(), company TEXT NOT NULL, title TEXT NOT NULL, location TEXT DEFAULT '全国', link TEXT DEFAULT '', requirement TEXT DEFAULT '', type TEXT DEFAULT '');`;

  const copySql = () => {
    navigator.clipboard.writeText(INIT_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-md p-4">
      <div className="bg-[#0c0c10] border border-[#27272a] w-full max-w-lg p-8 rounded-3xl shadow-2xl animate-in fade-in zoom-in duration-300">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-black text-white flex items-center gap-3 italic uppercase tracking-tighter">
            <Zap className="w-5 h-5 text-yellow-500" /> 数据库激活 (Docker版)
          </h2>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors">
            <XCircle className="w-7 h-7" />
          </button>
        </div>

        <div className="space-y-6 max-h-[70vh] overflow-y-auto pr-2 custom-scrollbar">
          
          <div className="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-xl">
             <div className="flex items-center gap-3 mb-2">
                <Database className="w-4 h-4 text-yellow-500" />
                <p className="text-[11px] font-bold text-yellow-500 uppercase">最后一步</p>
             </div>
             <p className="text-[10px] text-gray-400 leading-relaxed">
                你已经部署了 Docker 容器，现在需要在数据库里创建表。
                <br/>请在 Zeabur 的 PostgreSQL 页面操作。
             </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-[11px] font-bold text-gray-400 uppercase tracking-widest">操作流程：</h3>
            
            <div className="relative pl-4 border-l border-gray-800 space-y-6">
               <div className="relative">
                  <div className="absolute -left-[21px] top-0 w-3 h-3 rounded-full bg-blue-600 border-2 border-[#0c0c10]"></div>
                  <p className="text-xs text-white font-bold mb-1">打开 PostgreSQL Shell</p>
                  <p className="text-[10px] text-gray-500">在 Zeabur 点击 PostgreSQL -> Shell。</p>
                  <p className="text-[10px] text-gray-500 mt-1">输入 <code className="bg-gray-800 px-1 rounded text-white">psql</code> 回车。</p>
               </div>

               <div className="relative">
                  <div className="absolute -left-[21px] top-0 w-3 h-3 rounded-full bg-green-500 border-2 border-[#0c0c10] animate-pulse"></div>
                  <p className="text-xs text-white font-bold mb-2">粘贴建表命令</p>
                  
                  <div className="bg-black border border-gray-800 rounded-lg p-3">
                     <div className="flex justify-between items-center mb-2">
                        <span className="text-[10px] text-gray-500 uppercase font-mono">SQL</span>
                        <button 
                          onClick={copySql}
                          className="flex items-center gap-1.5 px-2 py-1 bg-green-600 hover:bg-green-500 text-white text-[10px] font-bold rounded transition-colors"
                        >
                          {copied ? <CheckCircle className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                          {copied ? '已复制' : '复制命令'}
                        </button>
                     </div>
                     <code className="block text-[9px] text-green-400 font-mono break-all leading-relaxed opacity-70">
                        {INIT_SQL}
                     </code>
                  </div>
                  <p className="text-[10px] text-gray-500 mt-2">粘贴并回车。看到 CREATE TABLE 即成功。</p>
               </div>
            </div>
          </div>

          <button
            onClick={() => window.location.reload()}
            className="w-full py-4 bg-white text-black rounded-xl font-bold text-xs uppercase hover:bg-blue-600 hover:text-white transition-all active:scale-95 shadow-lg mt-4"
          >
            我已完成，刷新页面
          </button>
        </div>
      </div>
    </div>
  );
};

export default SettingsModal;
